[config]
default_to_workspace = false

[env]
CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true

[tasks.test-bare]
args = [
    "test",
    "--package", "zcene-bare",
]
command = "cargo"

[tasks.build-bare-metal-playground]
#env = { "RUSTFLAGS" = "--cfg no_global_oom_handling" }
args = [
    "build",
    "--package", "zcene-bare-metal-playground",
    "--release",
    "--target", "zcene-bare-metal/x86_64.json",
    "-Z", "build-std=core,alloc,compiler_builtins",
    "-Z", "build-std-features=compiler-builtins-mem",
]
command = "cargo"

[tasks.build-bare-metal-playground-x86_64]
args = [
    "build",
    "--package", "zcene-bare-metal-playground-x86_64",
    "--release",
    "--target", "zcene-bare-metal/x86_64.json",
    "-Z", "build-std=core,alloc,compiler_builtins",
    "-Z", "build-std-features=compiler-builtins-mem",
]
command = "cargo"
dependencies = [
    "build-bare-metal-playground",
]

[tasks.run-bare-metal-playground-x86_64-uefi]
args = [
    #"-d", "int",
    "-no-reboot",
    "-nographic",
    "-cpu", "qemu64",
    "-drive", "format=raw,unit=1,file=target/x86_64/release/zcene-bare-metal-playground-x86_64-uefi.img",
    "-drive", "if=pflash,format=raw,unit=0,file=QEMU_UEFI_CODE-x86_64.fd",
    "-nic", "none",
    "-m", "1024",
    "-smp", "2",
]
command = "qemu-system-x86_64"
dependencies = [
    "build-bare-metal-playground-x86_64",
]

[tasks.prepare-bare-metal-playground-x86_64-uefi]
args = [
     "-o",
     "QEMU_UEFI_CODE-x86_64.fd",
     "https://retrage.github.io/edk2-nightly/bin/RELEASEX64_OVMF_CODE.fd",
]
command = "curl"

[tasks.clean]
command = "cargo"
args = ["clean"]
