[package]
name = "zcene-kernel"
version = "0.0.0"
edition = "2021"

[dependencies]
linked_list_allocator = "0.10"
zcene-core = { path = "../zcene-core" }
ztd = { git = "https://github.com/Stazer/ztd.git" }
spin = "*"
pc-keyboard = "*"
